-- Personal monitor layout.
-- Ported from monitors.conf (originally generated by nwg-displays 2025-12-26)
-- after the Omarchy "quattro" .conf -> .lua migration.
--
-- List monitors and supported modes: hyprctl monitors all

hl.env("GDK_SCALE", "1")

-- Fallback for any monitor not listed below.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@144", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "320x1440", scale = 1 })
